### ISSUE TITLE
MIUI开发版 后台服务启动失败

### ISSUE THREAD

**Issue by PlatypusPro** [shadowsocksr-backup/shadowsocksr-android#14]
刚刚手贱把辣鸡MIUI升级了，开机后SSR无法启动
升到`3.4.0.8`也有相同的问题
关闭分应用代理就正常，打开就报错，提示`后台服务启动失败：无法连接远程服务器……`
授予ROOT权限和重启都不行
LogCat是这个样子
```
10-24 19:18:58.468  8984  8984 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@8f3c31b
10-24 19:18:58.468  8984  8984 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@71e7cb8
10-24 19:18:58.474  8984  8984 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@90175f7
10-24 19:18:58.475  8984  8984 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@b9aac64
10-24 19:18:58.498  8984  8984 I JobManager: Found pending job request{id=3, tag=SSRSubUpdateJob}, canceling
10-24 19:18:58.521  8984  8984 E SQLiteDatabase: Error inserting persisted=false exact=false networkType=CONNECTED flexSupport=false isTransient=false tag=SSRSubUpdateJob intervalMs=86400000 numFailures=0 backoffPolicy=EXPONENTIAL flexMs=86400000 scheduledAt=1508843938516 requiresCharging=false requiresDeviceIdle=false backoffMs=30000 requirementsEnforced=true endMs=-1 _id=4 startMs=-1
10-24 19:18:58.521  8984  8984 E SQLiteDatabase: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: jobs._id (code 1555)
10-24 19:18:58.521  8984  8984 E SQLiteDatabase: at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
10-24 19:18:58.521  8984  8984 E SQLiteDatabase: at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
10-24 19:18:58.521  8984  8984 E SQLiteDatabase: at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
10-24 19:18:58.521  8984  8984 E SQLiteDatabase: at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
10-24 19:18:58.521  8984  8984 E SQLiteDatabase: at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1472)
10-24 19:18:58.521  8984  8984 E SQLiteDatabase: at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1343)
10-24 19:18:58.521  8984  8984 E SQLiteDatabase: at com.evernote.android.job.JobStorage.store(JobStorage.java:202)
10-24 19:18:58.521  8984  8984 E SQLiteDatabase: at com.evernote.android.job.JobStorage.put(JobStorage.java:109)
10-24 19:18:58.521  8984  8984 E SQLiteDatabase: at com.evernote.android.job.JobManager.schedule(JobManager.java:238)
10-24 19:18:58.521  8984  8984 E SQLiteDatabase: at com.evernote.android.job.JobRequest.schedule(JobRequest.java:337)
10-24 19:18:58.521  8984  8984 E SQLiteDatabase: at com.github.shadowsocks.job.SSRSubUpdateJob$.schedule(SSRSubUpdateJob.scala:35)
10-24 19:18:58.521  8984  8984 E SQLiteDatabase: at com.github.shadowsocks.Shadowsocks.onCreate(Shadowsocks.scala:339)
10-24 19:18:58.521  8984  8984 E SQLiteDatabase: at android.app.Activity.performCreate(Activity.java:6847)
10-24 19:18:58.521  8984  8984 E SQLiteDatabase: at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
10-24 19:18:58.521  8984  8984 E SQLiteDatabase: at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2677)
10-24 19:18:58.521  8984  8984 E SQLiteDatabase: at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2785)
10-24 19:18:58.521  8984  8984 E SQLiteDatabase: at android.app.ActivityThread.-wrap12(ActivityThread.java)
10-24 19:18:58.521  8984  8984 E SQLiteDatabase: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532)
10-24 19:18:58.521  8984  8984 E SQLiteDatabase: at android.os.Handler.dispatchMessage(Handler.java:102)
10-24 19:18:58.521  8984  8984 E SQLiteDatabase: at android.os.Looper.loop(Looper.java:163)
10-24 19:18:58.521  8984  8984 E SQLiteDatabase: at android.app.ActivityThread.main(ActivityThread.java:6321)
10-24 19:18:58.521  8984  8984 E SQLiteDatabase: at java.lang.reflect.Method.invoke(Native Method)
10-24 19:18:58.521  8984  8984 E SQLiteDatabase: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
10-24 19:18:58.521  8984  8984 E SQLiteDatabase: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
10-24 19:18:58.526  8984  8984 D JobProxy24: Schedule periodic jobInfo success, request{id=4, tag=SSRSubUpdateJob}, interval 00:00:00 (+1 day), flex 00:00:00 (+1 day)
10-24 19:18:58.530  8984  8984 W GoogleTagManager: Excessive refreshing detected; call ignored.
10-24 19:18:58.540  8984  8984 D ActivityThreadInjector: clearCachedDrawables.
10-24 19:18:58.562  8984  9021 I Adreno  : QUALCOMM build                   : 620c068, I09d312ff84
10-24 19:18:58.562  8984  9021 I Adreno  : Build Date                       : 08/07/17
10-24 19:18:58.562  8984  9021 I Adreno  : OpenGL ES Shader Compiler Version: XE031.09.00.04
10-24 19:18:58.562  8984  9021 I Adreno  : Local Branch                     : 
10-24 19:18:58.562  8984  9021 I Adreno  : Remote Branch                    : 
10-24 19:18:58.562  8984  9021 I Adreno  : Remote Branch                    : 
10-24 19:18:58.562  8984  9021 I Adreno  : Reconstruct Branch               : 
10-24 19:18:58.565  9022 11705 D PlatformJobService: Run job, request{id=4, tag=AclSyncJob:bypass-lan-china}, waited 00:10:32, start 00:00:00, end 00:00:00 (+28 days)
10-24 19:18:58.572  8984  9021 I OpenGLRenderer: Initialized EGL, version 1.4
10-24 19:18:58.572  8984  9021 D OpenGLRenderer: Swap behavior 1
10-24 19:18:58.575  9022 11705 I JobExecutor: Executing request{id=4, tag=AclSyncJob:bypass-lan-china}, context PlatformJobService
10-24 19:18:58.587  9022 11707 W Job     : Job requires charging, reschedule
10-24 19:18:58.587  9022 11707 I JobExecutor: Finished job{id=4, finished=true, result=RESCHEDULE, canceled=false, periodic=false, class=AclSyncJob, tag=AclSyncJob:bypass-lan-china}
10-24 19:18:58.614  9022 11707 D JobProxy24: Schedule one-off jobInfo success, request{id=6, tag=AclSyncJob:bypass-lan-china}, start 00:00:30, end 00:00:30 (+28 days)
10-24 19:18:58.620  9022 11705 D PlatformJobService: Finished job, request{id=4, tag=AclSyncJob:bypass-lan-china} RESCHEDULE
10-24 19:18:58.807  8984  9021 W OpenGLRenderer: cuilf pushLayerUpdate 309 delete mLayer: 0xd0c4e5c0, RenderLayer: 0xced88d80
10-24 19:19:01.115  9022  9076 W System.err: java.lang.SecurityException: get package uid: Neither user 10265 nor current process has android.permission.INTERACT_ACROSS_USERS.
10-24 19:19:01.116  9022  9076 W System.err: at android.os.Parcel.readException(Parcel.java:1683)
10-24 19:19:01.116  9022  9076 W System.err: at android.os.Parcel.readException(Parcel.java:1636)
10-24 19:19:01.116  9022  9076 W System.err: at android.net.IConnectivityManager$Stub$Proxy.establishVpn(IConnectivityManager.java:1924)
10-24 19:19:01.116  9022  9076 W System.err: at android.net.VpnService$Builder.establish(VpnService.java:769)
10-24 19:19:01.116  9022  9076 W System.err: at com.github.shadowsocks.ShadowsocksVpnService.startVpn(ShadowsocksVpnService.scala:469)
10-24 19:19:01.116  9022  9076 W System.err: at com.github.shadowsocks.ShadowsocksVpnService.handleConnection(ShadowsocksVpnService.scala:208)
10-24 19:19:01.116  9022  9076 W System.err: at com.github.shadowsocks.ShadowsocksVpnService.connect(ShadowsocksVpnService.scala:196)
10-24 19:19:01.116  9022  9076 W System.err: at com.github.shadowsocks.BaseService$$anonfun$startRunner$1.apply$mcV$sp(BaseService.scala:201)
10-24 19:19:01.117  9022  9076 W System.err: at com.github.shadowsocks.BaseService$$anonfun$startRunner$1.apply(BaseService.scala:201)
10-24 19:19:01.117  9022  9076 W System.err: at com.github.shadowsocks.BaseService$$anonfun$startRunner$1.apply(BaseService.scala:201)
10-24 19:19:01.117  9022  9076 W System.err: at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
10-24 19:19:01.117  9022  9076 W System.err: at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
10-24 19:19:01.117  9022  9076 W System.err: at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
10-24 19:19:01.117  9022  9076 W System.err: at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
10-24 19:19:01.117  9022  9076 W System.err: at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
10-24 19:19:01.117  9022  9076 W System.err: at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
10-24 19:19:01.117  9022  9076 W System.err: at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
10-24 19:19:01.120  8984  8984 E Shadowsocks: Error to start VPN service: 无法连接远程服务器: get package uid: Neither user 10265 nor current process has android.permission.INTERACT_ACROSS_USERS.
10-24 19:19:02.073  8984  8984 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@8cbea7b
10-24 19:19:02.073  8984  8984 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@6668098
10-24 19:19:02.251  8984  9021 W OpenGLRenderer: cuilf pushLayerUpdate 309 delete mLayer: 0xd0c4e5c0, RenderLayer: 0xced88d80
```
求助 QwQ

**Comment by 7alva7** [comment]
暂时用NAT模式凑合

**Comment by PlatypusPro** [comment]
嗯……好的
谢啦
